In [1]:
import numpy as np


In [3]:
mylist = [1,2,3]

In [4]:
np.array(mylist)

array([1, 2, 3])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.random.rand(10)*9+16

array([20.63221551, 22.07618086, 22.21009749, 19.96344067, 17.60073054,
       16.72324433, 23.26589008, 17.65152813, 20.83503346, 18.7679965 ])

In [10]:
np.random.rand(4,4)

array([[0.20858425, 0.29629751, 0.07474787, 0.16558604],
       [0.75385278, 0.85124134, 0.37654318, 0.88699842],
       [0.42327847, 0.47143399, 0.24075334, 0.47546321],
       [0.75347134, 0.63745781, 0.47745642, 0.50668483]])

In [ ]:
myIntArray = np.random.randint(1, 100, 10)      #(1 to 100 give me 10 random numbers)


array([69, 54, 28,  8, 11, 47, 44, 62, 14, 18], dtype=int32)