# Exercise
### Notebook created by Keshav Sriram Kumar

In this exercise you are going to analyze a yelp review, and try to determine the number of stars were given.

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

yelp = pd.read_csv('yelp.csv')

Read in the first 5 records.

In [23]:
yelp.head()

,business_id,date,review_id,stars,text,type,user_id,cool,useful,funny
0,9yKzy9PApeiPPOUJEtnvkg,2011-01-26,fWKvX83p0-ka4JS3dc6E5A,5,My wife took me here on my birthday for breakf...,review,rLtl8ZkDX5vH5nAx9C3q5Q,2,5,0
1,ZRJwVLyzEJq1VAihDhYiow,2011-07-27,IjZ33sJrzXqU-0X6U8NwyA,5,I have no idea why some people give bad review...,review,0a2KyEL0d3Yb1V6aivbIuQ,0,0,0
2,6oRAC4uyJCsJl1X0WZpVSA,2012-06-14,IESLBzqUCLdSzSqm0eCSxQ,4,love the gyro plate. Rice is so good and I als...,review,0hT2KtfLiobPvh6cDC8JQg,0,1,0
3,_1QQZuf4zZOyFCvXc0o6Vg,2010-05-27,G-WvGaISbqqaMHlNnByodA,5,"Rosie, Dakota, and I LOVE Chaparral Dog Park!!...",review,uZetl9T0NcROGOyFfughhg,1,2,0
4,6ozycU1RpktNG2-1BroVtw,2012-01-05,1uJFq2r5QfJG_6ExMRCaGw,5,General Manager Scott Petello is a good egg!!!...,review,vYmM4KTsC8ZfQBg-j5MWkw,0,0,0


Check the info of yelp

In [24]:
yelp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   business_id  10000 non-null  object
 1   date         10000 non-null  object
 2   review_id    10000 non-null  object
 3   stars        10000 non-null  int64 
 4   text         10000 non-null  object
 5   type         10000 non-null  object
 6   user_id      10000 non-null  object
 7   cool         10000 non-null  int64 
 8   useful       10000 non-null  int64 
 9   funny        10000 non-null  int64 
dtypes: int64(4), object(6)
memory usage: 781.4+ KB


Using CountVectorizor make the X the text, and make y the stars.  You will need to do a fit_transform on X.

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = yelp['text']
y = yelp['stars']
X = cv.fit_transform(X)

Do a train test split and a Naive Bayes on your data.

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3,random_state=87)

Determine the accuracy of your model by printing the classification report

In [27]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)

predictions = nb.predict(X_test)
nb.score(X_test, y_test)

from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predictions))
print("[TP, FP] \n [FN, TN]")

print(classification_report(y_test,predictions))


[[ 55  43  25  78  37]
 [ 12  17  39 181  23]
 [  3   7  42 334  47]
 [  7   5  20 787 240]
 [  2   5   4 451 536]]
[TP, FP] 
 [FN, TN]
              precision    recall  f1-score   support

           1       0.70      0.23      0.35       238
           2       0.22      0.06      0.10       272
           3       0.32      0.10      0.15       433
           4       0.43      0.74      0.54      1059
           5       0.61      0.54      0.57       998

    accuracy                           0.48      3000
   macro avg       0.46      0.33      0.34      3000
weighted avg       0.48      0.48      0.44      3000



Let's try to filter our data to the more extreme responses.  Make a new dataframe using only responses that are 1 star or 5 stars. <br><br>
yelp1or5 = yelp[(yelp['stars']==5) | (yelp['stars']==1)]
<br><br>
Redo the above steps using yelp1or5.  What is the accuracy of your model now? Print a classification report.  Why do you think there is a change?

In [28]:
yelp1or5 = yelp[(yelp['stars']==5) | (yelp['stars']==1)]

X = yelp1or5['text']
y = yelp1or5['stars']
X = cv.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3,random_state=87)
nb.fit(X_train, y_train)    

predictions = nb.predict(X_test)
nb.score(X_test, y_test)

from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predictions))
print("[TP, FP] \n [FN, TN]")

print(classification_report(y_test,predictions))

[[149  79]
 [ 35 963]]
[TP, FP] 
 [FN, TN]
              precision    recall  f1-score   support

           1       0.81      0.65      0.72       228
           5       0.92      0.96      0.94       998

    accuracy                           0.91      1226
   macro avg       0.87      0.81      0.83      1226
weighted avg       0.90      0.91      0.90      1226



Maybe, we removed (2, 3, 4)Stars from the dataframe and create a new dataframe for predicting only (1 or 5)stars so we reduced the load and made it easy to get more accurate.
